# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Features & bugfix CI

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: "Building"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
        directories: ["."]
    defaults:
      run:
        working-directory: ${{ matrix.directories }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn
    - run: yarn install --frozen-lockfile
    - run: yarn run build
#    - run: npm test
