# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Production CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: "Building"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
        directories: ["."]
    defaults:
      run:
        working-directory: ${{ matrix.directories }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn run build
  #    - run: npm test

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/now-deployment@v2
        with:
          zeit-token: ${{ secrets.ZEIT_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
          now-args: "--prod" #Optional
          now-org-id: ${{ secrets.ORG_ID}} #Required
          now-project-id: ${{ secrets.PROJECT_ID}} #Required
